404

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,12 +1,39 @@
 #!/usr/bin/env bash
 # Install and setup nginx server
 
-sudo apt-get -y update
-sudo apt-get -y install nginx
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
 sudo service nginx start
-replace="\\\terror_page 404 /404_costum.html;\n\tlocation = /404_costum.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
-echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_costum.html
-sudo sed -i "27i $replace" /etc/nginx/sites-available/default
-
+sudo echo -e \
+"http {
+root /var/www/domo;
+server {
+listen 80;
+server_name mrdomo.tech;
+error_page 404 = /error_404.html;
+rewrite ^/redirect_me/? \
+https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
+location / {
+index index.html;
+}
+location = /error_404.html {
+                internal;
+        }
+}
+}
+events {
+}" > /etc/nginx/nginx.conf
+sudo mkdir -p /var/www/domo
+sudo echo "Holberton School" > \
+/var/www/domo/index.html
+sudo touch /var/www/domo/error_404.html
+sudo echo "Ceci n'est pas une page" < \
+/var/www/domo/error_404.html
 sudo service nginx restart
-sudo service nginx reload
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
